[package]
name = "shika"
version = "0.1.0"
edition = "2021"

[dependencies]
http.workspace = true
hyper.workspace = true
tokio.workspace = true
hyper-util.workspace = true
http-body-util.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
